<div class="container">
    <div class="brand">
        <a href="">
            <img src="img/ff/fof.png" alt="Magz Logo">
        </a>
    </div>
    <div class="mobile-toggle">
        <a href="#" data-toggle="menu" data-target="#menu-list"><i class="ion-navicon-round"></i></a>
    </div>
    <div class="mobile-toggle">
        <a href="#" data-toggle="sidebar" data-target="#sidebar"><i class="ion-ios-arrow-left"></i></a>
    </div>
    <div id="menu-list">

        <div class="col-md-8 col-sm-12 text-left">
            <ul class="nav-icons">

                <li><a href="#">Artistas</a></li>
                <li><a href="#">Eventos</a></li>
                <li><a href="Registrarview">Registrar</a></li>
                <li><a href="login">Iniciar Sesión</a></li>
            </ul>
        </div>
    </div>